### ISSUE TITLE
Null state 

### ISSUE THREAD

**Issue by sEdsKi** [LordBoos/discord_game#49]
This automation works great

```
alias: AAA - Discord
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.discord_user_***
    attribute: voice_channel
    to: General
condition: []
action:
  - device_id: ***
    domain: cover
    entity_id: cover.guest_blind
    type: set_position
    position: 0
mode: single
```

The issue appears to be with the null state of the attribute. This automation won't trigger when leaving a channel and the state of voice_channel reverts to null.

```
alias: AAA - Discord
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.discord_user_***
    attribute: voice_channel
    to: null
condition: []
action:
  - device_id: ***
    domain: cover
    entity_id: cover.guest_blind
    type: set_position
    position: 100
mode: single
