### ISSUE TITLE
Configuration not getting validated

### ISSUE THREAD

**Issue by AndreiGr** [LordBoos/discord_game#50]
Hi there,

I installed the component from HACS, restarted the HA and then added the config part.

Now, I am trying to check my config and restart, but it's just stuck at checking the configuration, any ideas why this could be?

My config snippet:
```  
- platform: discord_game
   token: <token>
   members:
      - 287694783730810880

**Comment by LordBoos** [comment]
Hi, do you have `sensor:` there and token filled?
```
sensor:
  - platform: discord_game
    token: someSecretToken1234
    members:
      - 287694783730810880
```

**Comment by AndreiGr** [comment]
Small update
I just put the component config back into the .yaml to take the screenshot above, and now the config got validated without any issues.
No clue why it didn't want to validate it last night.

**Comment by LordBoos** [comment]
And which version are you using? If you are on the pre-release version (any 5.x.x), then you might also need to add `channels`.
```
sensor:
  - platform: discord_game
    token: someSecretToken1234
    members:
      - 287694783730810880
    channels:
      - someChannelUID
```
If you don't need channels feature, you can change your version to the release one, they are the same only pre-release has channels feature.
