### ISSUE TITLE
Setup in configuration.yaml not working anymore?

### ISSUE THREAD

**Issue by pixelwave** [LordBoos/discord_game#54]
I used to setup the discord_game in my configuration.yaml like this:

```
sensors:
  # Discord Online Status
  - platform: discord_game
    access_token: [...]
    image_format: webp # optional, available formats are: png, webp, jpeg, jpg
    members:
      - 4941...
```

But that does not seem to work anymore after a recent home assistant update?
