### ISSUE TITLE
It is possible to poll the sensor for different actions reported by Discord?

### ISSUE THREAD

**Issue by NMe84** [LordBoos/discord_game#7]
I would like to use the state my Discord reports in some automations, so that I can for instance automatically turn the brightness of my lights down if I start playing a game. The way things are now I don't think you can do anything besides seeing whether or not my account is online, which it is pretty much 24/7.

Is it currently possible to watch game, streaming, listening or watching status for use in automation and am I just missing it? And if it's not possible, is this something that would be possible to add and you would consider adding?

**Comment by LordBoos** [comment]
Yes that is possible by creating custom template sensors from the attributes of the main sensor.
```
sensor:
  - platform: discord_game
    token: !secret discord_api_key
    members:
      - Username#number
  - platform: template
    sensors:
      discord_username_number_game:
        value_template: '{{ states.sensor.discord_username_number.attributes.game}}'
```
